### ISSUE TITLE
запрос на "СПИСОК ЗАДАЧ (С ФИЛЬТРАЦИЕЙ)" перестал работать

### ISSUE THREAD

**Issue by m-abyzov** [OlegShatin/EgeWebApiProto#26]
Сейчас выдаёт 500. Раньше всё норм было.
![500](https://user-images.githubusercontent.com/15013638/28610436-07dfeb86-71f1-11e7-98ca-9b0dde61059e.png)

**Comment by OlegShatin** [comment]
@Mishabuzov fixed
